### ISSUE TITLE
Can not load any hlt file. Any way to know why?

### ISSUE THREAD

**Issue by wizzup** [fohristiwhirl/chlorine#10]
The replay file is tested on halite site and it is view able. [replay.zip](https://github.com/fohristiwhirl/chlorine/files/1449887/replay.zip) (github only allowed zip upload)

I try `File -> Open` and `drag-n-drop` too, still the same.

How can I get more information on this? Do you have option to turn on more verbose logging?

![2017-11-07-190214_719x300_scrot](https://user-images.githubusercontent.com/342500/32492907-709312f8-c3ee-11e7-807f-44d99fdaa608.png)

I just clone the repo

![2017-11-07-190400_716x219_scrot](https://user-images.githubusercontent.com/342500/32492921-82c33778-c3ee-11e7-9653-33d3b32de33b.png)

**Comment by tarriel** [comment]
not sure, this file works for me.  did you do the npm install?

**Comment by wizzup** [comment]
I got this warnings when `npm install` but doesn't look like any problem.

    [nix-shell:~/works/coding_challenges/halite/repos/chlorine]$ npm install
    npm WARN Chlorine@1.0.3 No repository field.
    npm WARN Chlorine@1.0.3 No license field.

I think the problem is maybe only for me, that why I ask for way to get some logging message.

If you can provide some logging in the future, please do.

**Comment by rooklift** [comment]
I've no idea at present. However, I've just now added a few lines of logging to the code. If you could get this latest version, retry, and then go into the developer tools (via file menu) and check the console there? Thanks.

**Comment by wizzup** [comment]
I think I know the source of the problem . 

I got following log from `Console`

    Trying to load ../../mybots/haskell/last_replay.hlt
    chlorine_renderer.html:154 Error 2
    chlorine_renderer.html:155 Error: spawn /data/works/coding_challenges/halite/repos/chlorine/node_modules/node-zstandard/bin/zstd.linux64 ENOENT
        at exports._errnoException (util.js:1050:11)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
        at onErrorNT (internal/child_process.js:367:16)
        at _combinedTickCallback (internal/process/next_tick.js:80:11)
        at process._tickCallback (internal/process/next_tick.js:104:9)

Try running the `zstd.linux64` and found that it can't run due to missing `ld-linux`

    $ file ./node_modules/node-zstandard/bin/zstd.linux64 
    ./node_modules/node-zstandard/bin/zstd.linux64: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=1140a78f74182371415d88c46eb6faedd2ef55c2, not stripped

This is `known` nodejs problem on NixOS. There is no problem with your code. I don't think you can do anything to fix it.

Thank you for your time and your works.

**Comment by wizzup** [comment]
I just hack it to work on NixOS. If anyone interested just checkout my [fork](https://github.com/wizzup/chlorine)

**Comment by tarriel** [comment]
hmmm.  I run ubuntu and didn't have any problems?  I did already have node & npm installed if that made a difference, I also installed electron locally mostly because I couldn't work out how to install it system wide.
