### ISSUE TITLE
Feature request : add frame number on renderer window

### ISSUE THREAD

**Issue by wizzup** [fohristiwhirl/chlorine#13]
The top-right corner look like a good place to add current frame number.

![2017-12-11-174921_796x411_scrot](https://user-images.githubusercontent.com/342500/33827651-a23a57cc-de9b-11e7-9f80-5f61ca29cbb4.png)

**Comment by rooklift** [comment]
Hmm top right is used for distances, if you click on an object then a different object.

Does your OS have window title bars? On most OS's the frame number is there...

**Comment by wizzup** [comment]
If you can, please don't use title bar. I am using tiling window manager ([xmonad](http://xmonad.org/)) and [xmobar](https://archives.haskell.org/projects.haskell.org/xmobar/) for status bar. Window title is basically useless for me. 

But if you really want to use window title. Please put the frame number before anything to prevent clipping. The xmobar space  for window title I have is not much.

**Comment by rooklift** [comment]
Try it now I guess.

**Comment by wizzup** [comment]
Wonderful!

![2017-12-13-121843_797x436_scrot](https://user-images.githubusercontent.com/342500/33922815-e3fef0ea-dfff-11e7-8315-cf3831d280cc.png)
