### ISSUE TITLE
Feature request: see unit data

### ISSUE THREAD

**Issue by yngvix** [fohristiwhirl/chlorine#3]
It would be helpful to see the info of the unit under mouse pointer: ID, coordinates, and health.

**Comment by rooklift** [comment]
Yeah. Something like that is for the future. Maybe in a day or two (though I need to get on with writing my actual bot... :)

**Comment by rooklift** [comment]
I've made some progress on this. Click on an entity to see some info.

**Comment by yngvix** [comment]
This is great, thank you very much! Chlorine is very useful for debugging.
